part = {
    "juz 1" : "https://youtu.be/so-QHLIy2V0",
    # "juz 2" : "https://youtu.be/ttTGple9mxQ",
    # "juz 3" : "https://youtu.be/T_aopS_-sAs",
    # "juz 4" : "https://youtu.be/2qFGReWoA7I",
    # "juz 5" : "https://youtu.be/PSN7Jpxhvhg",
    # "juz 6" : "https://youtu.be/bEF69avUACA",
    # "juz 7" : "https://youtu.be/LZfYmVE5yBs",
    # "juz 8" : "https://youtu.be/bPnvAs3L9gc",
    # "juz 9" : "https://youtu.be/lVNp0ejF8ws",
    # "juz 10" : "https://youtu.be/I6g5cNGtn3I",
    # "juz 11" : "https://youtu.be/UhgoOLtpGow",
    # "juz 12" : "https://youtu.be/jVQrkmbLsHk",
    # "juz 13" : "https://youtu.be/Tt55jykMmrk",
    # "juz 14" : "https://youtu.be/f4cgBjwEcj0",
    # "juz 15" : "https://youtu.be/5aWuAR7oSlw",
    # "juz 16" : "https://youtu.be/9h0hLLlPxuY",
    # "juz 17" : "https://youtu.be/CBHEUsWu4RA",
    # "juz 18" : "https://youtu.be/oPCqZac6-XU",
    # "juz 19" : "https://youtu.be/zXfEixoY9UI",
    # "juz 20" : "https://youtu.be/HRpe_ytMQ7k",
    # "juz 21" : "https://youtu.be/B36uMXLywHY",
    # "juz 22" : "https://youtu.be/FMTewq7Bvxw",
    # "juz 23" : "https://youtu.be/x8-DumYiv6o",
    # "juz 24" : "https://youtu.be/ld6ic12J_uw",
    # "juz 25" : "https://youtu.be/alU_Xk2QFAw",
    # "juz 26" : "https://youtu.be/xpp-f_4ABiA",
    # "juz 27" : "https://youtu.be/A-6H5EaWBd8",
    # "juz 28" : "https://youtu.be/f2QC3WcbrEQ",
    # "juz 29" : "https://youtu.be/eAXjTbIKmlk",
    # "juz 30" : "https://youtu.be/KoXobclIh14",
}